---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/kubeconfig_myapp-eks-cluster
      
    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: /root/nginx-config.yaml
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /root/kubeconfig_myapp-eks-cluster
        namespace: my-app